### PR TITLE
#10 adding markup and placeholder for articles

### PR DESCRIPTION
**Pull request by davexoxide**

### CODE REVIEW

**Comment by sirkitree** [comment]
kinda nice to just work with html and css for a change, eh? Are you still working on this or ok to merge?

**Comment by davexoxide** [comment]
Still working on it. Want to swap out the placeholders w/ real content.
I noticed that not much has been done in terms of responsive, is that right?

**Comment by sirkitree** [comment]
I'm using bootstrap as much as possible to give us that responsiveness, but I haven't tested responsiveness much yet

**Comment by davexoxide** [comment]
@sirkitree this isn't perfect, some responsive work can be improved but I'd say this is good enough to get in so we can continue building upon it.

**Comment by sirkitree** [comment]
Thanks!

**Pull request merged**
